# Generated by Django 3.2.18 on 2023-04-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('url', models.CharField(max_length=200, unique=True)),
                ('press', models.CharField(max_length=100)),
                ('journalist', models.CharField(max_length=20)),
                ('summary', models.CharField(max_length=1000)),
                ('article_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('section', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'news_article_info',
                'managed': False,
            },
        ),
    ]
