# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

# 네이버크롤링후 요약 테스트 문 
POST http://localhost:10000/crawl/naver/
Content-Type: application/json

{
  "url" : "https://n.news.naver.com/article/018/0005472525"

}

###
# test
POST http://127.0.0.1:8000/board/crawl/
Content-Type: application/json
{
  "url" : "https://n.news.naver.com/article/018/0005472525"
}


###
POST http://127.0.0.1:8000/board/summarize/
Content-Type: application/json

{
  "url" : "https://n.news.naver.com/article/658/0000039535?type=main"

}